//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietluong
    {
        public int maluong { get; set; }
        public int manv { get; set; }
        public int thang { get; set; }
        public int nam { get; set; }
        public decimal luongcoban { get; set; }
        public Nullable<decimal> phucap { get; set; }
        public Nullable<decimal> thuong { get; set; }
        public Nullable<decimal> phat { get; set; }
        public Nullable<decimal> tongluong { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
