//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class congviec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public congviec()
        {
            this.nhacnhoes = new HashSet<nhacnho>();
            this.PhanCongs = new HashSet<PhanCong>();
            this.TimeLogs = new HashSet<TimeLog>();
            this.lichcas = new HashSet<lichca>();
        }
    
        public int macv { get; set; }
        public int malv { get; set; }
        public string tieude { get; set; }
        public string mota { get; set; }
        public System.DateTime thoigian_bd { get; set; }
        public System.DateTime thoigian_kt { get; set; }
        public string mucdo_uutien { get; set; }
        public string trangthai { get; set; }
        public Nullable<int> nguoigiao { get; set; }
        public byte tiendo { get; set; }
        public string loaicv { get; set; }
    
        public virtual lichlamviec lichlamviec { get; set; }
        public virtual nhanvien nhanvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhacnho> nhacnhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeLog> TimeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lichca> lichcas { get; set; }
    }
}
