//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dangnhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dangnhap()
        {
            this.nhanviens = new HashSet<nhanvien>();
            this.quenmks = new HashSet<quenmk>();
        }
    
        public int madangnhap { get; set; }
        public string tendangnhap { get; set; }
        public string matkhauHash { get; set; }
        public string email { get; set; }
        public string tennguoidung { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaysua { get; set; }
        public int mavt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhanvien> nhanviens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quenmk> quenmks { get; set; }
        public virtual vaitro vaitro { get; set; }
    }
}
