//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class duan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public duan()
        {
            this.lichlamviecs = new HashSet<lichlamviec>();
        }
    
        public int mada { get; set; }
        public string tenduan { get; set; }
        public string mota { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public Nullable<System.DateTime> ngaydukienhoanthanh { get; set; }
        public string trangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lichlamviec> lichlamviecs { get; set; }
    }
}
