//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichlamviec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lichlamviec()
        {
            this.congviecs = new HashSet<congviec>();
        }
    
        public int malv { get; set; }
        public Nullable<int> manv { get; set; }
        public Nullable<int> mada { get; set; }
        public string tieude { get; set; }
        public string loai { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public System.DateTime ngayketthuc { get; set; }
        public string ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<congviec> congviecs { get; set; }
        public virtual duan duan { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
