//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichca
    {
        public int malichca { get; set; }
        public int manv { get; set; }
        public System.DateTime ngay { get; set; }
        public System.TimeSpan giobd { get; set; }
        public System.TimeSpan giokt { get; set; }
        public Nullable<int> macv { get; set; }
    
        public virtual congviec congviec { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
