//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class luongcoban
    {
        public int mamuc { get; set; }
        public int manv { get; set; }
        public decimal luongcoban1 { get; set; }
        public Nullable<System.DateTime> ngayhieuluc { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
