//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhacnho
    {
        public int manhacnho { get; set; }
        public int macv { get; set; }
        public System.DateTime thoigiannhac { get; set; }
        public string hinhthuc { get; set; }
        public Nullable<bool> isSent { get; set; }
    
        public virtual congviec congviec { get; set; }
    }
}
