//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ql_nhanvienEntities : DbContext
    {
        public ql_nhanvienEntities()
            : base("name=ql_nhanvienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitietluong> chitietluongs { get; set; }
        public virtual DbSet<chucvu> chucvus { get; set; }
        public virtual DbSet<congviec> congviecs { get; set; }
        public virtual DbSet<dangnhap> dangnhaps { get; set; }
        public virtual DbSet<duan> duans { get; set; }
        public virtual DbSet<lichlamviec> lichlamviecs { get; set; }
        public virtual DbSet<luongcoban> luongcobans { get; set; }
        public virtual DbSet<nhacnho> nhacnhoes { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<PhanCong> PhanCongs { get; set; }
        public virtual DbSet<quenmk> quenmks { get; set; }
        public virtual DbSet<TimeLog> TimeLogs { get; set; }
        public virtual DbSet<vaitro> vaitroes { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<lichca> lichcas { get; set; }
    }
}
