//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quenmk
    {
        public int tokenid { get; set; }
        public int madangnhap { get; set; }
        public string token { get; set; }
        public System.DateTime expirytime { get; set; }
        public Nullable<bool> isused { get; set; }
    
        public virtual dangnhap dangnhap { get; set; }
    }
}
