//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLog
    {
        public int matimelog { get; set; }
        public int manv { get; set; }
        public int macv { get; set; }
        public System.DateTime batdau { get; set; }
        public System.DateTime ketthuc { get; set; }
        public Nullable<int> tongtg { get; set; }
        public string ghichu { get; set; }
    
        public virtual congviec congviec { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
